// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github.get').default>>>>
    }
    '/api/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google.get').default>>>>
    }
    '/api/habits/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/[id].patch').default>>>>
    }
    '/api/habits/:id/journal': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/[id]/journal.post').default>>>>
    }
    '/api/habits/:id/react': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/[id]/react.post').default>>>>
    }
    '/api/habits/:id/share': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/[id]/share.post').default>>>>
    }
    '/api/habits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/index.post').default>>>>
    }
    '/api/habits/shared': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/shared.get').default>>>>
    }
    '/api/me/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me/notifications.get').default>>>>
    }
    '/api/notifications/:id/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/[id]/respond.post').default>>>>
    }
    '/api/users/:login/habits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[login]/habits.get').default>>>>
    }
    '/api/users/:login': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[login]/index.get').default>>>>
    }
    '/api/users': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.patch').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/cors.dev').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/sync-variables': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/sync-variables.post').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}